language: java
sudo: false
services: mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS skilltracker;'
install: true
script: "mvn clean install"
cache:
  directories:
  - $HOME/.m2
