language: java
sudo: false
services: mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS skilltracker;'
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('pass@word1') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo service mysql restart
install: true
script: "mvn clean install"
cache:
  directories:
  - $HOME/.m2
